# Generated by Django 5.1.4 on 2025-04-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boshishorin',
            name='tavsif_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='boshishorin',
            name='tavsif_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='boshishorin',
            name='tavsif_uz',
            field=models.TextField(null=True),
        ),
    ]
