# Generated by Django 5.1.4 on 2025-03-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoshqarmaTarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OliyTalImFanInnovatsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='oliytalim/')),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OzbekistonQonunlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='qonunlar/')),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OzKuchiniYoqotgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='yoqotgan_hujjatlar/')),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrezidentFarmonlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='farmonlar/')),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarkibiyTuzilma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViloyatQarorlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('fayl', models.FileField(upload_to='viloyat_qarorlari/')),
                ('sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='elonvatadbirlar',
            name='image',
            field=models.ImageField(upload_to='Images/elon_va_tadbirlar/', verbose_name='Asosiy Rasm'),
        ),
        migrations.AlterField(
            model_name='elonvatadbirlarrasmlar',
            name='image',
            field=models.ImageField(upload_to='Images/elon_va_tadbirlar/', verbose_name='Elon va Tadbir Rasmi'),
        ),
        migrations.AlterField(
            model_name='matbuotxizmati',
            name='image',
            field=models.ImageField(upload_to='Images/matbuot/', verbose_name='Asosiy Rasm'),
        ),
        migrations.CreateModel(
            name='BoShIshOrin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(max_length=100)),
                ('joylashuv', models.CharField(max_length=100)),
                ('sana', models.DateField()),
                ('tavsif', models.TextField()),
                ('boshqarma_tarix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BoShIshOrin', to='news_app.boshqarmatarixi', verbose_name='Tegishli boshqarma tarix')),
            ],
        ),
        migrations.CreateModel(
            name='QabulJadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('lavozim', models.CharField(max_length=255)),
                ('qabul_vaqti', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('boshqarma_tarix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QabulJadvali', to='news_app.boshqarmatarixi', verbose_name='Tegishli QabulJadvali')),
            ],
        ),
        migrations.CreateModel(
            name='Rahbariyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('rasmi', models.ImageField(upload_to='Images/rahbariyat/')),
                ('lavozim', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('boshqarma_tarix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rahbariyatlar', to='news_app.boshqarmatarixi', verbose_name='Tegishli Rahbariyat')),
            ],
        ),
    ]
