# Generated by Django 5.1.4 on 2025-03-29 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_boshqarmatarixi_oliytalimfaninnovatsiya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oliytalimfaninnovatsiya',
            name='uzbek_qonunlari',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OliyTalImFanInnovatsiya', to='news_app.ozbekistonqonunlari', verbose_name='Tegishli OliyTalImFanInnovatsiya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ozkuchiniyoqotgan',
            name='uzbek_qonunlari',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OzKuchiniYoqotgan', to='news_app.ozbekistonqonunlari', verbose_name='Tegishli OzKuchiniYoqotgan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prezidentfarmonlari',
            name='uzbek_qonunlari',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PrezidentFarmonlari', to='news_app.ozbekistonqonunlari', verbose_name='Tegishli PrezidentFarmonlari'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarkibiytuzilma',
            name='boshqarma_tarix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TarkibiyTuzilma', to='news_app.boshqarmatarixi', verbose_name='Tegishli TarkibiyTuzilma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viloyatqarorlari',
            name='uzbek_qonunlari',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ViloyatQarorlari', to='news_app.ozbekistonqonunlari', verbose_name='Tegishli ViloyatQarorlari'),
            preserve_default=False,
        ),
    ]
