# Generated by Django 5.1.4 on 2025-04-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_boshishorin_tavsif_en_boshishorin_tavsif_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prezidentfarmonlari',
            name='uzbek_qonunlari',
        ),
        migrations.RemoveField(
            model_name='viloyatqarorlari',
            name='uzbek_qonunlari',
        ),
        migrations.RemoveField(
            model_name='ozkuchiniyoqotgan',
            name='uzbek_qonunlari',
        ),
        migrations.AlterField(
            model_name='boshqarmatarixi',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='boshqarmatarixi',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='boshqarmatarixi',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='boshqarmatarixi',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='murojat',
            name='murojat_kimga',
            field=models.CharField(choices=[('rahbar', 'Rahbar'), ('urinbosar', 'O‘rinbosar')], default='rahbar', max_length=20),
        ),
        migrations.DeleteModel(
            name='OliyTalImFanInnovatsiya',
        ),
        migrations.DeleteModel(
            name='PrezidentFarmonlari',
        ),
        migrations.DeleteModel(
            name='ViloyatQarorlari',
        ),
        migrations.DeleteModel(
            name='OzbekistonQonunlari',
        ),
        migrations.DeleteModel(
            name='OzKuchiniYoqotgan',
        ),
    ]
