# Generated by Django 5.1.4 on 2025-03-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_oliytalimfaninnovatsiya_uzbek_qonunlari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('murojat_kimga', models.CharField(max_length=255)),
                ('murojat_turi', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('ismi', models.CharField(max_length=255)),
                ('otasining_ismi', models.CharField(blank=True, max_length=255, null=True)),
                ('kompaniyaning_nomi', models.CharField(blank=True, max_length=255, null=True)),
                ('boglanish_malumotlari', models.CharField(max_length=255)),
                ('pochta_manzil', models.EmailField(max_length=254)),
                ('mirojat_matni', models.TextField()),
                ('hujjatlar', models.FileField(blank=True, null=True, upload_to='murojatlar/')),
                ('tel_raqam', models.CharField(max_length=20)),
            ],
        ),
    ]
