# Generated by Django 5.1.4 on 2025-04-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_remove_prezidentfarmonlari_uzbek_qonunlari_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erishilganyutuqlar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name=' ilangan Sana'),
        ),
    ]
