# Generated by Django 5.1.4 on 2025-04-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_erishilganyutuqlar_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matbuotxizmati',
            options={'ordering': ['-id'], 'verbose_name': 'Yangiliklar ', 'verbose_name_plural': 'Yangiliklar '},
        ),
        migrations.AlterModelOptions(
            name='matbuotxizmatirasmlar',
            options={'verbose_name': 'Yangiliklar Rasmi', 'verbose_name_plural': 'Yangiliklar Rasmlari'},
        ),
        migrations.RemoveField(
            model_name='qabuljadvali',
            name='email',
        ),
        migrations.RemoveField(
            model_name='qabuljadvali',
            name='ism',
        ),
        migrations.RemoveField(
            model_name='qabuljadvali',
            name='lavozim',
        ),
        migrations.RemoveField(
            model_name='qabuljadvali',
            name='qabul_vaqti',
        ),
        migrations.RemoveField(
            model_name='qabuljadvali',
            name='telefon',
        ),
        migrations.AddField(
            model_name='qabuljadvali',
            name='image',
            field=models.ImageField(default=1, upload_to='Images/qabul_jadvali/', verbose_name='Asosiy Rasm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabuljadvali',
            name='matn',
            field=models.TextField(default=1, verbose_name='Politexnikum haqida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qabuljadvali',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Politexnikum nomi'),
            preserve_default=False,
        ),
    ]
