# Generated by Django 5.1.4 on 2025-03-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_murojat'),
    ]

    operations = [
        migrations.AddField(
            model_name='boshishorin',
            name='rasm',
            field=models.ImageField(default=1, upload_to='Images/bo_shish_orin/'),
            preserve_default=False,
        ),
    ]
