# Generated by Django 5.1.4 on 2025-03-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_boshishorin_rasm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boshishorin',
            old_name='rasm',
            new_name='image',
        ),
    ]
