# Generated by Django 5.1.4 on 2025-04-25 18:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_matbuotxizmati_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabuljadvali',
            name='matn',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
