# Generated by Django 5.1.4 on 2025-03-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_rename_rasm_boshishorin_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rahbariyat',
            old_name='rasmi',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='TarkibiyTuzilma',
        ),
    ]
