# Generated by Django 5.1.4 on 2025-04-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_alter_qabuljadvali_matn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qabuljadvali',
            name='boshqarma_tarix',
        ),
    ]
