# Generated by Django 5.1.4 on 2025-04-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_rename_rasmi_rahbariyat_image_delete_tarkibiytuzilma'),
    ]

    operations = [
        migrations.AddField(
            model_name='boshqarmatarixi',
            name='image',
            field=models.ImageField(default=1, upload_to='Images/boshqarma_haqida/'),
            preserve_default=False,
        ),
    ]
