# Generated by Django 5.1.4 on 2025-04-29 06:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_remove_qabuljadvali_boshqarma_tarix'),
    ]

    operations = [
        migrations.AddField(
            model_name='qabuljadvali',
            name='matn_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='qabuljadvali',
            name='matn_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='qabuljadvali',
            name='matn_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='qabuljadvali',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Politexnikum nomi'),
        ),
        migrations.AddField(
            model_name='qabuljadvali',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Politexnikum nomi'),
        ),
        migrations.AddField(
            model_name='qabuljadvali',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Politexnikum nomi'),
        ),
    ]
