# Generated by Django 5.1.4 on 2025-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_qabuljadvali_matn_en_qabuljadvali_matn_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matbuotxizmati',
            options={'ordering': ['-id'], 'verbose_name': 'Yangiliklar', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='qabuljadvali',
            options={'verbose_name': 'Qabul Jadvali', 'verbose_name_plural': 'Qabul Jadvali'},
        ),
        migrations.AlterField(
            model_name='erishilganyutuqlar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan Sana'),
        ),
    ]
