# Generated by Django 5.1.4 on 2025-04-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_boshqarmatarixi_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boshqarmatarixi',
            options={'verbose_name': 'Boshqarma Haqida', 'verbose_name_plural': 'Boshqarma Haqida'},
        ),
    ]
