# Generated by Django 5.1.4 on 2025-04-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_alter_boshqarmatarixi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MurojatHammuallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familya', models.CharField(max_length=255)),
                ('ismi', models.CharField(max_length=255)),
                ('otasining_ismi', models.CharField(blank=True, max_length=255, null=True)),
                ('pochta_manzil', models.EmailField(max_length=254)),
                ('murojat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murojat_hammuallif', to='news_app.murojat', verbose_name='Tegishli Murojat')),
            ],
        ),
    ]
