# Generated by Django 5.1.4 on 2025-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_alter_matbuotxizmati_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boshishorin',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AddField(
            model_name='boshqarmatarixi',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AddField(
            model_name='elonvatadbirlar',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AddField(
            model_name='erishilganyutuqlar',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AddField(
            model_name='matbuotxizmati',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AddField(
            model_name='qabuljadvali',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
