# Generated by Django 5.1.4 on 2025-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_murojathammuallif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boshishorin',
            name='image',
            field=models.ImageField(upload_to='Images/bo_shish_orin/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='boshqarmatarixi',
            name='content',
            field=models.TextField(verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='boshqarmatarixi',
            name='image',
            field=models.ImageField(upload_to='Images/boshqarma_haqida/', verbose_name='Asosiy Rasm'),
        ),
        migrations.AlterField(
            model_name='murojat',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Qoyilgan Sana'),
        ),
        migrations.AlterField(
            model_name='murojat',
            name='murojat_kimga',
            field=models.CharField(choices=[('rahbar', 'Rahbar'), ('urinbosar', "O'rinbosar")], default='rahbar', max_length=20),
        ),
        migrations.AlterField(
            model_name='murojat',
            name='murojat_turi',
            field=models.CharField(choices=[('shikoyat', 'Shikoyat'), ('taklif', 'Taklif'), ('savol', 'Savol')], default='savol', max_length=20),
        ),
        migrations.AlterField(
            model_name='rahbariyat',
            name='image',
            field=models.ImageField(upload_to='Images/rahbariyat/', verbose_name='Rasm'),
        ),
    ]
